config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'

  resources :recipes do
  	resources :comments, only: [:create]
  end

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, except: [:destroy]

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
	before_save {self.email = email.downcase}
	validates :chefname, presence: true, length: {maximum: 30}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},
					format: { with: VALID_EMAIL_REGEX },
					uniqueness: { case_sensitive: false }
	has_many :recipes, dependent: :destroy
	has_secure_password
	validates :password, presence: true, length: {minimum: 5}, allow_nil: true
	has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord

	validates :description, presence: :true, length: { minimu: 4, maximum: 140}
	belongs_to :chef
	belongs_to :recipe
	validates :chef_id, presence: true
	validates :recipe_id, presence: true
	default_scope -> { order(updated_at: :desc) }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

	validates :name, presence: true, length: { minimum: 3, maximum: 25 }
	validates_uniqueness_of :name
	has_many :recipe_ingredients
	has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	validates :name, presence: true
	validates :description, presence: true, length: {minimum: 5, maximum: 500}
	belongs_to :chef
	validates :chef_id, presence: true
	default_scope -> { order(updated_at: :desc) }
	has_many :recipe_ingredients
	has_many :ingredients, through: :recipe_ingredients
	has_many :comments, dependent: :destroy
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
	belongs_to :ingredient
	belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_chef, :logged_in?

	def current_chef
		@current_chef ||= Chef.find(session[:chef_id]) if session[:chef_id]	
	end

	def logged_in?
		!!current_chef
	end

	def require_user
		if !logged_in?
			flash[:danger] = "You must be logged in to perform that action"
			redirect_to root_path
		end
	end

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

	before_action :set_chef, only: [:show, :edit, :update, :destroy]
	before_action :require_same_user, only: [:edit, :update]
	before_action :require_admin, only: [:destroy]

	def index
		@chefs = Chef.paginate(page: params[:page], per_page: 5)
	end

	def new
		@chef = Chef.new
	end

	def create
		@chef = Chef.new(chef_params)
		if @chef.save
			session[:chef_id] = @chef.id
			flash[:success] = "Welcome #{@chef.chefname} to MyRecipes App!"
			cookies.signed[:chef_id] = @chef.id
			redirect_to chef_path(@chef)
		else
			render 'new'
		end
	end

	def show
		@chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 5)
	end

	def edit
	end

	def update
		if @chef.update(chef_params)
			flash[:success] = "Your account was updated successfully"
			redirect_to @chef
		else
			render 'edit'
		end
	end

	def destroy
		if !@chef.admin?
			@chef.destroy
			flash[:danger] = "Chef and all associated recipes have been deleted!"
			redirect_to chefs_path
		end
	end

	private

		def chef_params
			params.require(:chef).permit(:chefname, :email,
			 :password, :password_confirmation)
		end

		def set_chef
			@chef = Chef.find(params[:id])
		end

		def require_same_user
			if current_chef != @chef and !current_chef.admin?
				flash[:danger] = "You can only edit or delete your own account"
				redirect_to chefs_path
			end
		end

		def require_admin
			if logged_in? && !current_chef.admin?
				flash[:danger] = "Only admin users can perform that action"
				redirect_to root_path
			end
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :require_user

	def create
		@recipe = Recipe.find(params[:recipe_id])
		@comment = @recipe.comments.build(comment_params)
		@comment.chef = current_chef
		if @comment.save
			ActionCable.server.broadcast "comments", render(partial: 'comments/comment', object: @comment)
			# flash[:success] = "Comment was successfully created"
			# redirect_to recipe_path(@recipe)
		else
			flash[:danger] = "Comment was not created"
			redirect_back(fallback_location: root_path)
		end
	end

	private

		def comment_params
			params.require(:comment).permit(:description)
		end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

	before_action :set_ingredient, only: [:edit, :update, :show]
	before_action :require_admin, except: [:show, :index]

	def new
		@ingredient = Ingredient.new
	end

	def create
		@ingredient = Ingredient.new(ingredient_params)
		if @ingredient.save
			flash[:success] = "Ingredient was successfully created!"
			redirect_to ingredient_path(@ingredient)
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @ingredient.update(ingredient_params)
			flash[:success] = "Ingredient name was updated successfully!"
			redirect_to ingredient_path(@ingredient)
		else
			render 'edit'
		end
	end

	def show
		@ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
	end

	def index
		@ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
	end

	private

		def require_admin
			if !logged_in? || (logged_in? and !current_chef.admin?)
				flash[:danger] = "Only admin users can perform that action"
				redirect_to ingredient_path
			end
		end

		def ingredient_params
			params.require(:ingredient).permit(:name)
		end

		def set_ingredient
			@ingredient = Ingredient.find(params[:id])
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to recipes_path if logged_in?
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	before_action :set_recipe, only: [:show, :edit, :update, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@recipes = Recipe.paginate(page: params[:page], per_page: 5)
	end

	def show
		@comment = Comment.new
		@comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.chef = current_chef
		if @recipe.save
			flash[:success] = "Recipe was created successfully!"
			redirect_to recipe_path(@recipe)
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @recipe.update(recipe_params)
			flash[:success] = "Recipe was updated successfully!"
			redirect_to recipe_path(@recipe)
		else
			render 'edit'
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id]).destroy
		flash[:success] = "Recipe deleted successfully!"
		redirect_to recipes_path
	end

	private

		def set_recipe
			@recipe = Recipe.find(params[:id])
		end

		def recipe_params
			params.require(:recipe).permit(:name, :description, ingredient_ids: [])
		end

		def require_same_user
			if current_chef != @recipe.chef and !current_chef.admin?
				flash[:danger] = "You can only edit or delete your own recipes"
				redirect_to recipes_path
			end
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		chef = Chef.find_by(email: params[:session][:email].downcase)
		if chef && chef.authenticate(params[:session][:password])
			session[:chef_id] = chef.id
			cookies.signed[:chef_id] = chef.id
			flash[:success] = "You have successfully logged in"
			redirect_to chef
		else
			flash.now[:danger] = "There was something wrong with your login information"
			render 'new'
		end
	end

	def destroy
		session[:chef_id] = nil
		flash[:success]  = "You have successfully logged out"
		redirect_to root_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def avatar_image(user, options = {size: 80})
		size = options[:size]
		img_url = "https://image.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg"
		image_tag(img_url, alt: user.chefname, class: "img-circle user-image")
	end

end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>
<div class="row">
	<div class="col-md-12">
		<%= form_for(@chef, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="col-form-label col-md-2">
					<%= f.label :chefname, "Name" %>
				</div>
				<div class="col-md-8">
					<%= f.text_field :chefname, class: "form-control", placeholder: "Enter your name", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-form-label col-md-2">
					<%= f.label :email %>
				</div>
				<div class="col-md-8">
					<%= f.email_field :email, rows: 10, class: "form-control", placeholder: "Enter your email" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-form-label col-md-2">
					<%= f.label :password %>
				</div>
				<div class="col-md-8">
					<%= f.password_field :password, rows: 10, class: "form-control", placeholder: "Choose a password" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-form-label col-md-2">
					<%= f.label :password_confirmation, "Confirm password" %>
				</div>
				<div class="col-md-8">
					<%= f.password_field :password_confirmation, rows: 10, class: "form-control", placeholder: "Password confirmation" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-10">
					<%= f.submit(@chef.new_record? ? "Sign Up" : "Update",
					 class: "btn btn-primary btn-lg") %>
				</div>
			</div>
			<div class="col-md-4 offset-md-2">
				[ <%= link_to "Cancel request and return to recipes listing", recipes_path %>]
			</div>
		<% end %>
	</div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit your profile" %>
<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "Showing all Chefs" %>

<div align="center">
	<%= will_paginate %>
	<% @chefs.each do |chef| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 offset-md-4">
					<li> <%= link_to avatar_image(chef), chef_path(chef) %></li>
					<li class="chef-title"> <%= link_to chef.chefname.capitalize, chef_path(chef) %></li>
					<li><small><%= pluralize(chef.recipes.count, "recipe") if chef.recipes %></small></li>

					<% if logged_in? && current_chef.admin? && !chef.admin?%>
					<li><%= link_to "Delete chef", chef_path(chef), method: :delete, data: {confirm: "Are you sure you want to delete this chef?"}%></li>
					<% end %>
				</div>
			</div>
		</ul>
	<% end %>
	<%= will_paginate %>
</div>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Sign up for the application" %>
<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef #{@chef.chefname}'s Profile" %>
<div class="row">
	<div class="col-md-4 offset-md-4 center">
		<%= avatar_image(@chef) %>
	</div>
</div>

<% if @chef.recipes.count != 0 %>
	<h4 align="center"><%= @chef.chefname %>'s recipes</h4>
	<div align="center"></div>
	<%= will_paginate @chef_recipes %>
	<%= render 'recipes/recipe', obj: @chef_recipes %>
	<%= will_paginate @chef_recipes %>
<% else %>
	<h4 align="center">No recipes yet</h4>
<% end %>

app/views/comments/_comment.html.erb
<div class="row">
	<div class = "col-md-2">
		<section class="chef_info center">
			<%= avatar_image(comment.chef, size: 60) %>
		</section>
	</div>
	<div class="col-md-8 card">
		<p><%=comment.description %></p>
		<p>
			<span class="quiet">
				<small>Created: <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.chef.chefname %></small>
			</span>
		</p>
	</div>
</div>

app/views/comments/_comments.html.erb
<div align="center">
	<%= will_paginate comments %>
</div>
<% comments.each do |comment| %>
	<%= render(partial: 'comments/comment', object: comment) %>
<% end %>
<div align="center">
	<%= will_paginate comments %>
</div>

app/views/ingredients/_form.html.erb
<%= render 'shared/errors', obj: @ingredient %>
<div class="row">
	<div class="col-md-12">
		<%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="col-form-label col-md-2">
					<%= f.label :name %>
				</div>
				<div class="col-md-8">
					<%= f.text_field :name, class: "form-control", placeholder: "Enter ingredient", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-10">
					<%= f.submit(@ingredient.new_record? ? "Add ingredient" : "Update ingredient", class: "btn btn-primary btn-lg") %>
				</div>
			</div>
			<div class="col-md-4 offset-md-2">
				[ <%= link_to "Cancel request and return to recipes listing", recipes_path %>]
			</div>
		<% end %>
	</div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge"><%= link_to ingredient.name, ingredient_path(ingredient) %> &nbsp;</span>

app/views/ingredients/edit.html.erb
<%= render 'shared/page_title', title: "Enter new name" %>
<%= render 'form' %>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: "Available Ingredients" %>

<div align="center">
	<%= will_paginate %>
	<% @ingredients.each do |ing| %>
		<ul class="listing">
			<div class="row">
				<div class="card col-md-4 offset-md-4">
					<li class="chef-title"> <%= link_to ing.name.capitalize, ingredient_path(ing) %></li>
					<li><small><%= pluralize(ing.recipes.count, "recipe") if ing.recipes %></small></li>

					<% if logged_in? && current_chef.admin? %>
					<li><%= link_to "Edit", edit_ingredient_path(ing)%></li>
					<% end %>
				</div>
			</div>
		</ul>
	<% end %>
	<%= will_paginate %>
</div>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: "Enter a new ingredient" %>
<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: @ingredient.name %>

<% if @ingredient.recipes.count != 0 %>
	<h4 align="center">Recipes containing <%= @ingredient.name %></h4>
	<div align="center"></div>
	<%= will_paginate @ingredient_recipes %>
	<%= render 'recipes/recipe', obj: @ingredient_recipes %>
	<%= will_paginate @ingredient_recipes %>
<% else %>
	<h4 align="center">No recipes yet</h4>
<% end %>

app/views/layouts/_footer.html.erb
    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
      </div>
    </footer>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-10 md-offset-1">
		<% flash.each do |name, msg| %>
		<div class="alert alert-<%= name %>">
			<a href="#" class="close" data-dismiss="alert">&#215</a>
			<%= msg %>
		</div>
    	<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "MyRecipies", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "Chefs", chefs_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Recipes", recipes_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ingredients
        </a>


        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Ingredients", ingredients_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <% Ingredient.all.each do |ing| %>
            <%= link_to ing.name.capitalize, ingredient_path(ing), class: "dropdown-item" %>
          <% end %>
          <% if logged_in? && current_chef.admin? %>
          <div class="dropdown-divider"></div>
          <%= link_to "Add Ingredient", new_ingredient_path, class: "dropdown-item" %>
          <% end %>
        </div>

      </li>

      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_chef.chefname %> <%= "(Admin)" if current_chef.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", chef_path(current_chef), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_chef_path(current_chef), class: "dropdown-item" %>
            <%= link_to "Create Recipe", new_recipe_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
        <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to MyRecipies</h1>
	<h2>The best recipe sharing app!</h2>
	<p><%= link_to "Sign Up Now", signup_path, class: "btn btn-danger btn-lg" %></p>
</div>

<div class="row">
<div class="col-lg-4">
  <h2>Safari bug warning!</h2>
  <p class="text-danger">As of v9.1.2, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
  <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
</div>
<div class="col-lg-4">
  <h2>Heading</h2>
  <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
</div>
<div class="col-lg-4">
  <h2>Heading</h2>
  <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
  <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
</div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>
<div class="row">
	<div class="col-md-12">
		<%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="col-form-label col-md-2">
					<%= f.label :name %>
				</div>
				<div class="col-md-8">
					<%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
				</div>
			</div>

			<div class="form-group">
				<div class="row">
					<div class="col-md-8 form-check form-check-inline">
						<%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb|%>
							<% cb.label(class: "form-check-label input-checkbox") {cb.check_box(class: "form-check-input") + cb.text} %>
						<% end %>
					</div>
				</div>
			</div>

			<div class="form-group">
				<div class="col-form-label col-md-2">
					<%= f.label :description %>
				</div>
				<div class="col-md-8">
					<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-10">
					<%= f.submit class: "btn btn-primary btn-lg" %>
				</div>
			</div>
			<div class="col-md-4 offset-md-2">
				[ <%= link_to "Cancel request and return to recipes listing", recipes_path %>]
			</div>
		<% end %>
	</div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
	<div class="row">
		<div class="col-md-2">
			<section class="center">
				<%= avatar_image(recipe.chef) %>
			</section>
		</div>
		<div class="col-md-8 card card-body bg-light">
			<h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
			<p><%= truncate(recipe.description, length: 150) %></p>
			<% if recipe.ingredients.any? %>
				<p>Ingredients: <%= render recipe.ingredients %></p>
			<% end %>
			<p>
				<span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at)%> ago by <%= link_to recipe.chef.chefname, chef_path(recipe.chef)%>
					| <%= pluralize(recipe.comments.count, "comment") %>
				</small></span>
			</p>
			<% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
				<div class="recipe-actions">
					<%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
					<%= link_to "Delete", recipe_path(recipe), method: :delete,
					data: {confirm: "Are you sure you wnat to delete this recipe?"}, class: "btn btn-xs btn-danger" %>
				</div>
			<% end %>
		</div>
	</div>


<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing recipe" %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "showing all recipes" %>

<div align="center">
	<%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
	<%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new recipe" %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>
<div class="card card-body bg-light col-md-offset-2">
	<h4 class="center description">
		<strong>Steps:</strong>
	</h4>
	<hr />
	<%= simple_format(@recipe.description) %>
	<hr />
	<% if @recipe.ingredients.any? %>
		<p>Ingredients: <%= render @recipe.ingredients %></p>
	<% end %>
	<div class="float-right">
		<p class="center">
			<em>Created by:</em>
		</p>
		<p class="center">
			<%= link_to avatar_image(@recipe.chef), chef_path(@recipe.chef) %>
		</p>
		<p class="center">
			<small><%= @recipe.chef.chefname.capitalize %></small>
			<div class="float-right"><%= time_ago_in_words(@recipe.created_at) %> ago</div>
		</p>
	</div>
	<div class="recipe-actions">

		<% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
			<%= link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
			<%= link_to "Delete", recipe_path(@recipe), method: :delete,
					data: {confirm: "Are you sure you wnat to delete this recipe?"}, class: "btn btn-xs btn-danger" %>
		<% end %>

		<%= link_to "Return to recipes list", recipes_path, class: "btn btn-xs btn-primary" %>
	</div>
</div>

<% if logged_in? %>
	<div class="row">
		<div class="col-md-12">
			<h3>Comments: </h3>
			<hr/>
			<%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>

				<div class="form-group">
					<div class="col-form-label col-md-2">
						<%= f.label :description, "Comment" %>
					</div>
					<div class="col-md-8">
						<%= f.text_area :description, rows: 2, class: "form-control", placeholder: "Enter your comment" %>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-10">
						<%= f.submit "Submit a comment", class: "btn btn-primary btn-lg" %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
<% end %>


<% if @recipe.comments.count != 0 %>
	<div class="row">
		<div class="col-md-8">
			<h3>Prior Comments: </h3>
			<div id="messages">
				<%= render partial: 'comments/comments', object: @comments %>
			</div>
		</div>
	</div>
<% else %>
	<div class="row">
		<div class="col-md-8">
			<h3>No Comments Yet</h3>
		</div>
	</div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="card text-white bg-danger mb-3">
				<div class="card-header">
					<%= pluralize(obj.errors.count, "error") %>
				prohibited this <%= obj.class %> from being saved:
				</div>
			<div class="card-body">
			<p class="card-text">
				<ul>
					<% obj.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</p>
			</div>
			</div>
		</div>
	</div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr />